In [1]:
import pandas as pd
from datetime import datetime
import pickle

filepath = "data/Games.csv"

pd.set_option('display.max_columns', None)

In [2]:
df_games = pd.read_csv(filepath)

df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72753 entries, 0 to 72752
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            72753 non-null  int64
 1   gameDateTimeEst   72753 non-null  object
 2   hometeamCity      72753 non-null  object
 3   hometeamName      72753 non-null  object
 4   hometeamId        72753 non-null  int64
 5   awayteamCity      72753 non-null  object
 6   awayteamName      72753 non-null  object
 7   awayteamId        72753 non-null  int64
 8   homeScore         72753 non-null  int64
 9   awayScore         72753 non-null  int64
 10  winner            72753 non-null  int64
 11  gameType          72753 non-null  object
 12  gameSubtype       74 non-null     object
 13  gameLabel         3945 non-null   object
 14  gameSubLabel      231 non-null    object
 15  seriesGameNumber  5738 non-null   float64
 16  attendance        871 non-null    float64
 17  arenaId           72753 non-null  int64
 18  arenaName         874 non-null    object
 19  arenaCity         874 non-null    object
 20  arenaState        865 non-null    object
 21  officials         874 non-null    object
 22  year              72753 non-null  int64
 23  month             72753 non-null  int64
 24  day               72753 non-null  int64
 25  DoW               72753 non-null  int64
 26  time              72753 non-null  object
dtypes: float64(2), int64(11), object(14)
memory usage: 15.0+ MB

/tmp/ipykernel_167045/168054654.py:1: DtypeWarning: Columns (12,14,18,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_games = pd.read_csv(filepath)

In [3]:
df_games['gameDate'] = pd.to_datetime(df_games['gameDateTimeEst']).dt.date
df_games.sort_values(by='gameDate', inplace=True)
df_games.reset_index(drop=True, inplace=True)

In [8]:
df_games.isna().sum()

gameId                  0
gameDateTimeEst         0
hometeamCity            0
hometeamName            0
hometeamId              0
awayteamCity            0
awayteamName            0
awayteamId              0
homeScore               0
awayScore               0
winner                  0
gameType                0
gameLabel           68808
seriesGameNumber    67015
attendance          71882
arenaId                 0
year                    0
month                   0
day                     0
DoW                     0
time                    0
gameDate                0
dtype: int64

In [7]:
df_games.drop(df_games.iloc[:, [12, 14, 18, 19, 20, 21]], axis=1, inplace=True)

In [9]:
df_games.to_csv("data/Games.csv", index=False)

In [3]:

df_games["year"] = pd.to_datetime(df_games["gameDateTimeEst"]).dt.year
df_games["month"] = pd.to_datetime(df_games["gameDateTimeEst"]).dt.month
df_games["day"] = pd.to_datetime(df_games["gameDateTimeEst"]).dt.day
df_games["DoW"] = pd.to_datetime(df_games["gameDateTimeEst"]).dt.day_of_week
df_games["time"] = pd.to_datetime(df_games["gameDateTimeEst"]).dt.time
df_games.head(3)

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,...,arenaId,arenaName,arenaCity,arenaState,officials,year,month,day,DoW,time
0,22500774,2026-02-10 22:30:00,Los Angeles,Lakers,1610612747,San Antonio,Spurs,1610612759,108,136,...,1000069,Crypto.com Arena,Los Angeles,CA,"Scott Foster, Leon Wood, Justin Van Duyne",2026,2,10,1,22:30:00
1,22500773,2026-02-10 21:00:00,Phoenix,Suns,1610612756,Dallas,Mavericks,1610612742,120,111,...,1000159,Mortgage Matchup Center,Phoenix,AZ,"JB DeRosa, Tyler Ford, Intae Hwang",2026,2,10,1,21:00:00
2,22500772,2026-02-10 20:00:00,Houston,Rockets,1610612745,LA,Clippers,1610612746,102,95,...,215,Toyota Center,Houston,TX,"Curtis Blair, Nick Buchert, Matt Kallio",2026,2,10,1,20:00:00

In [40]:
df_games_playoff_2023 = df_games[(df_games["gameType"] == "Playoffs") & (df_games["year"] == 2023)]
#df_games_playoff_2023.drop(columns=['attendance', 'arenaId','arenaName', 'arenaCity', 'arenaState', 'officials', 'year', 'month',
#       'day', 'DoW', 'time'], inplace=True)

In [66]:
df_games_playoff_2023

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,...,arenaId,arenaName,arenaCity,arenaState,officials,year,month,day,DoW,time
3642,42200405,2023-06-12 20:30:00,Denver,Nuggets,1610612743,Miami,Heat,1610612748,94,89,...,1000046,NaN,NaN,NaN,NaN,2023,6,12,0,20:30:00
3643,42200404,2023-06-09 20:30:00,Miami,Heat,1610612748,Denver,Nuggets,1610612743,95,108,...,1000100,NaN,NaN,NaN,NaN,2023,6,9,4,20:30:00
3644,42200403,2023-06-07 20:30:00,Miami,Heat,1610612748,Denver,Nuggets,1610612743,94,109,...,1000100,NaN,NaN,NaN,NaN,2023,6,7,2,20:30:00
3645,42200402,2023-06-04 20:00:00,Denver,Nuggets,1610612743,Miami,Heat,1610612748,108,111,...,1000046,NaN,NaN,NaN,NaN,2023,6,4,6,20:00:00
3646,42200401,2023-06-01 20:30:00,Denver,Nuggets,1610612743,Miami,Heat,1610612748,104,93,...,1000046,NaN,NaN,NaN,NaN,2023,6,1,3,20:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3721,42200151,2023-04-16 15:00:00,Memphis,Grizzlies,1610612763,Los Angeles,Lakers,1610612747,112,128,...,242,NaN,NaN,NaN,NaN,2023,4,16,6,15:00:00
3722,42200161,2023-04-15 20:30:00,Sacramento,Kings,1610612758,Golden State,Warriors,1610612744,126,123,...,609,NaN,NaN,NaN,NaN,2023,4,15,5,20:30:00
3723,42200131,2023-04-15 18:00:00,Cleveland,Cavaliers,1610612739,New York,Knicks,1610612752,97,101,...,1000006,NaN,NaN,NaN,NaN,2023,4,15,5,18:00:00
3724,42200111,2023-04-15 15:30:00,Boston,Celtics,1610612738,Atlanta,Hawks,1610612737,112,99,...,17,NaN,NaN,NaN,NaN,2023,4,15,5,15:30:00
3725,42200121,2023-04-15 13:00:00,Philadelphia,76ers,1610612755,Brooklyn,Nets,1610612751,121,101,...,419,NaN,NaN,NaN,NaN,2023,4,15,5,13:00:00

In [42]:
df_games_west_2023 = df_games_playoff_2023[(df_games_playoff_2023["gameLabel"] == "West - First Round") & (df_games_playoff_2023["seriesGameNumber"] == 1)]
df_games_east_2023 = df_games_playoff_2023[(df_games_playoff_2023["gameLabel"] == "East - First Round") & (df_games_playoff_2023["seriesGameNumber"] == 1)]
df_games_west_2023

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,...,arenaId,arenaName,arenaCity,arenaState,officials,year,month,day,DoW,time
3718,42200141,2023-04-16 22:30:00,Denver,Nuggets,1610612743,Minnesota,Timberwolves,1610612750,109,80,...,1000046,NaN,NaN,NaN,NaN,2023,4,16,6,22:30:00
3719,42200171,2023-04-16 20:00:00,Phoenix,Suns,1610612756,Los Angeles,Clippers,1610612746,110,115,...,1000051,NaN,NaN,NaN,NaN,2023,4,16,6,20:00:00
3721,42200151,2023-04-16 15:00:00,Memphis,Grizzlies,1610612763,Los Angeles,Lakers,1610612747,112,128,...,242,NaN,NaN,NaN,NaN,2023,4,16,6,15:00:00
3722,42200161,2023-04-15 20:30:00,Sacramento,Kings,1610612758,Golden State,Warriors,1610612744,126,123,...,609,NaN,NaN,NaN,NaN,2023,4,15,5,20:30:00

In [81]:

df_games_boston_2023 = df_games_playoff_2023[(df_games_playoff_2023["hometeamName"] == "Celtics") | (df_games_playoff_2023["awayteamName"] == "Celtics")]
df_games_boston_2023_1 = df_games_boston_2023[df_games_boston_2023["seriesGameNumber"] == 1]
df_games_boston_2023_1.drop(df_games_boston_2023_1.iloc[:, [12, 14, 18, 19, 20, 21]], axis=1, inplace=True)

/tmp/ipykernel_17112/3026075276.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_games_boston_2023_1.drop(df_games_boston_2023_1.iloc[:, [12, 14, 18, 19, 20, 21]], axis=1, inplace=True)

In [82]:
df_games_boston_2023_1

,gameId,gameDateTimeEst,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,winner,gameType,gameLabel,seriesGameNumber,attendance,arenaId,year,month,day,DoW,time
3656,42200301,2023-05-17 20:30:00,Boston,Celtics,1610612738,Miami,Heat,1610612748,116,123,1610612748,Playoffs,East - Conf. Finals,1.0,NaN,17,2023,5,17,2,20:30:00
3680,42200211,2023-05-01 19:30:00,Boston,Celtics,1610612738,Philadelphia,76ers,1610612755,115,119,1610612755,Playoffs,East - Conf. Semifinals,1.0,NaN,17,2023,5,1,0,19:30:00
3724,42200111,2023-04-15 15:30:00,Boston,Celtics,1610612738,Atlanta,Hawks,1610612737,112,99,1610612738,Playoffs,East - First Round,1.0,NaN,17,2023,4,15,5,15:30:00

In [35]:
team_round1_west = [(row["hometeamId"], row["awayteamId"]) for index, row in df_games_east_2023.iterrows()]
for i, team_id in enumerate(team_round1_west):
    print(i, team_id[0], team_id[1])

0 1610612749 1610612748
1 1610612739 1610612752
2 1610612738 1610612737
3 1610612755 1610612751

In [32]:
team_round1_west = [(row["hometeamId"], row["awayteamId"]) for index, row in df_games_west_2023.iterrows()]
team_round1_east = [(row["hometeamId"], row["awayteamId"]) for index, row in df_games_east_2023.iterrows()]
team_round1_west[0][0]

1610612743